# Generated by Django 2.2 on 2019-05-05 15:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_auto_20190504_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='likes',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
