# Generated by Django 2.2 on 2019-05-05 15:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_lesson_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='likes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
