# Generated by Django 2.2 on 2019-05-05 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190505_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='likes',
            new_name='stars',
        ),
    ]
