# Generated by Django 2.2 on 2019-05-05 16:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190505_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='votes',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='stars',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
