# Generated by Django 2.2 on 2019-05-05 16:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190505_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='stars',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
